import { useMemo, useState } from 'react';
import { useTranslation } from 'react-i18next';
import { MapContainer, Marker, Popup, TileLayer } from 'react-leaflet';
import L from 'leaflet';
import { ArrowRight, CalendarCheck, Car, Check, Clock3, Star } from 'lucide-react';
import Header from '../components/Header';
import Footer from '../components/Footer';
import { stations } from '../data/stations';
import { api } from '../services/api';

const markerIcon = (station) => new L.DivIcon({ className: 'station-marker', html: `<div style="background:${station.accent}"><span>${station.name.slice(0, 1)}</span><b>${station.freeSlots}</b></div>`, iconSize: [40, 40], iconAnchor: [20, 20] });

export default function HomePage() {
  const { t } = useTranslation();
  const [selected, setSelected] = useState(stations[0]);
  const [form, setForm] = useState({ bay: '', car_brand: '', car_year: '', problem_description: '' });
  const [state, setState] = useState({ sending: false, success: false, error: '' });
  const bays = useMemo(() => selected?.bays || [], [selected]);
  const selectStation = (id) => { setSelected(stations.find((item) => item.id === Number(id))); setForm((value) => ({ ...value, bay: '' })); };
  const update = (key) => (event) => setForm((value) => ({ ...value, [key]: event.target.value }));
  const submit = async (event) => {
    event.preventDefault(); setState({ sending: true, success: false, error: '' });
    try {
      await api.post('/tickets/create/', { station: selected.id, bay: Number(form.bay), car_brand: form.car_brand, car_year: Number(form.car_year), problem_description: form.problem_description }, localStorage.getItem('token'));
      setState({ sending: false, success: true, error: '' }); setForm({ bay: '', car_brand: '', car_year: '', problem_description: '' });
    } catch { setState({ sending: false, success: false, error: t('home.bookingFailed') }); }
  };
  return <div className="min-h-screen bg-slate-50 text-slate-900 transition-colors dark:bg-slate-950 dark:text-slate-100"><Header /><main>
    <Hero t={t} />
    <section id="stations" className="mx-auto max-w-7xl px-4 py-12 md:px-8"><SectionTitle eyebrow={t('home.stations')} title={t('home.stationsText')} /><div className="grid gap-5 lg:grid-cols-[1.35fr_.65fr]"><div className="h-[540px] overflow-hidden rounded-3xl border border-slate-200 bg-white p-2 shadow-soft dark:border-white/10 dark:bg-slate-900"><MapContainer center={[42.8746, 74.6122]} zoom={12} scrollWheelZoom className="z-0"><TileLayer attribution="&copy; OpenStreetMap contributors" url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png" />{stations.map((station) => <Marker key={station.id} position={[station.latitude, station.longitude]} icon={markerIcon(station)} eventHandlers={{ click: () => selectStation(station.id) }}><Popup><PopupCard station={station} t={t} onBook={() => { selectStation(station.id); document.querySelector('#booking')?.scrollIntoView({ behavior: 'smooth' }); }} /></Popup></Marker>)}</MapContainer></div><div className="max-h-[540px] space-y-2 overflow-auto rounded-3xl border border-slate-200 bg-white p-3 shadow-soft dark:border-white/10 dark:bg-slate-900">{stations.map((station) => <StationCard key={station.id} station={station} selected={selected.id === station.id} onSelect={() => selectStation(station.id)} t={t} />)}</div></div></section>
    <section id="booking" className="mx-auto max-w-7xl px-4 py-12 md:px-8"><div className="grid gap-8 rounded-3xl bg-slate-900 p-6 text-white shadow-2xl shadow-slate-900/20 md:p-10 lg:grid-cols-[.75fr_1.25fr]"><div><div className="grid h-11 w-11 place-items-center rounded-xl bg-cyan-400/15 text-cyan-300"><CalendarCheck /></div><h2 className="mt-5 text-3xl font-bold">{t('home.bookingTitle')}</h2><p className="mt-3 leading-7 text-slate-300">{t('home.bookingText')}</p><div className="mt-8 rounded-2xl border border-white/10 bg-white/5 p-4"><div className="flex items-center gap-3"><Logo station={selected} /><div><p className="text-xs text-slate-400">{t('home.selected')}</p><p className="font-semibold">{selected.name}</p></div></div><Occupancy station={selected} t={t} light /></div></div><form onSubmit={submit} className="grid content-start gap-4 sm:grid-cols-2"><Field label={t('home.station')}><select value={selected.id} onChange={(e) => selectStation(e.target.value)}>{stations.map((station) => <option key={station.id} value={station.id}>{station.name}</option>)}</select></Field><Field label={t('home.bay')}><select required value={form.bay} onChange={update('bay')}><option value="">{t('home.bayPlaceholder')}</option>{bays.map((item) => <option key={item.id} value={item.id}>{item.name} · {t(`specialties.${item.category}`)}</option>)}</select></Field><Field label={t('home.carBrand')}><input required value={form.car_brand} onChange={update('car_brand')} placeholder="Toyota, BMW..." /></Field><Field label={t('home.year')}><input required value={form.car_year} onChange={update('car_year')} type="number" min="1990" max="2030" placeholder="2020" /></Field><Field label={t('home.problem')} className="sm:col-span-2"><textarea required value={form.problem_description} onChange={update('problem_description')} rows="4" placeholder={t('home.problemPlaceholder')} /></Field>{state.success && <p className="sm:col-span-2 flex items-center gap-2 rounded-xl bg-emerald-400/15 px-4 py-3 text-sm text-emerald-200"><Check size={17} />{t('home.sent')}</p>}{state.error && <p className="sm:col-span-2 rounded-xl bg-red-400/15 px-4 py-3 text-sm text-red-100">{state.error}</p>}<button disabled={state.sending} className="sm:col-span-2 inline-flex items-center justify-center gap-2 rounded-xl bg-cyan-400 px-5 py-3.5 font-semibold text-slate-950 transition hover:bg-cyan-300 disabled:opacity-60">{t('home.sendBooking')}<ArrowRight size={18} /></button></form></div></section>
  </main><Footer /></div>;
}
function Hero({ t }) { return <section className="relative overflow-hidden"><div className="absolute inset-0 bg-[radial-gradient(circle_at_20%_5%,rgba(34,211,238,.18),transparent_29%),radial-gradient(circle_at_90%_15%,rgba(59,130,246,.15),transparent_24%)]" /><div className="relative mx-auto max-w-7xl px-4 pb-16 pt-16 md:px-8 md:pb-24 md:pt-24"><div className="max-w-3xl"><p className="mb-5 inline-flex items-center gap-2 rounded-full border border-cyan-200 bg-cyan-50 px-3 py-1.5 text-sm font-medium text-cyan-700 dark:border-cyan-400/20 dark:bg-cyan-400/10 dark:text-cyan-300"><span className="h-2 w-2 rounded-full bg-cyan-500" />{t('home.eyebrow')}</p><h1 className="text-4xl font-bold tracking-tight md:text-6xl">{t('home.title')}</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-slate-600 dark:text-slate-300">{t('home.description')}</p><div className="mt-8 flex gap-3"><a href="#stations" className="inline-flex items-center gap-2 rounded-xl bg-cyan-500 px-5 py-3 font-semibold text-slate-950 shadow-lg shadow-cyan-500/25">{t('home.findStation')}<ArrowRight size={18} /></a><a href="#booking" className="rounded-xl border border-slate-200 bg-white px-5 py-3 font-semibold dark:border-white/15 dark:bg-white/5">{t('home.createBooking')}</a></div></div></div></section>; }
function StationCard({ station, selected, onSelect, t }) { return <button onClick={onSelect} className={`w-full rounded-2xl p-3 text-left transition ${selected ? 'bg-cyan-50 ring-1 ring-cyan-300 dark:bg-cyan-400/10 dark:ring-cyan-400/40' : 'hover:bg-slate-50 dark:hover:bg-white/5'}`}><div className="flex gap-3"><Logo station={station} /><div className="min-w-0 flex-1"><div className="flex justify-between gap-2"><p className="truncate font-semibold">{station.name}</p><span className="flex items-center gap-1 text-sm font-medium"><Star className="fill-amber-400 text-amber-400" size={14} />{station.rating}</span></div><p className="mt-1 text-xs text-cyan-600 dark:text-cyan-300">{t(`specialties.${station.specialization}`)}</p><Occupancy station={station} t={t} /></div></div></button>; }
function PopupCard({ station, t, onBook }) { return <div className="min-w-[210px]"><div className="flex gap-2"><Logo station={station} /><div><p className="font-bold">{station.name}</p><p className="text-xs">{station.address}</p></div></div><Occupancy station={station} t={t} /><Queue station={station} t={t} /><button onClick={onBook} className="mt-3 w-full rounded-lg bg-cyan-500 px-3 py-2 text-sm font-semibold text-slate-950">{t('home.createBooking')}</button></div>; }
function Occupancy({ station, t, light = false }) { return <div className={`mt-2 flex flex-wrap gap-x-3 gap-y-1 text-xs ${light ? 'text-slate-300' : 'text-slate-500 dark:text-slate-400'}`}><span className="flex items-center gap-1"><Car size={13} />{station.inService} {t('home.inService')}</span><span className="flex items-center gap-1 text-emerald-600 dark:text-emerald-400"><span className="h-1.5 w-1.5 rounded-full bg-emerald-500" />{station.freeSlots} {t('home.freeSlots')}</span><span className="flex items-center gap-1"><Clock3 size={13} />{station.queueCount}</span></div>; }
function Queue({ station, t }) { return <div className="mt-3 border-t pt-2"><p className="mb-1 text-xs font-semibold">{t('home.queueNow')}</p>{station.currentQueue.length ? <div className="flex flex-wrap gap-1">{station.currentQueue.map((item) => <span key={item.label} className="rounded bg-slate-100 px-1.5 py-0.5 text-[10px] dark:bg-slate-800">#{item.position} {item.label}</span>)}</div> : <p className="text-xs text-emerald-600">{t('home.queueEmpty')}</p>}</div>; }
function Logo({ station }) { return station.logo ? <img src={station.logo} alt="" className="h-10 w-10 rounded-xl object-cover" /> : <span style={{ backgroundColor: station.accent }} className="grid h-10 w-10 shrink-0 place-items-center rounded-xl font-bold text-white">{station.name.slice(0, 1)}</span>; }
function SectionTitle({ eyebrow, title }) { return <div className="mb-6"><p className="text-sm font-semibold text-cyan-600 dark:text-cyan-300">{eyebrow}</p><h2 className="mt-1 text-3xl font-bold tracking-tight">{title}</h2></div>; }
function Field({ label, children, className = '' }) { return <label className={`grid gap-1.5 text-sm font-medium text-slate-200 ${className}`}><span>{label}</span>{children}</label>; }
