import { Bell, CircleUserRound, Coins, Globe2, History, MessageCircle, Palette, Save, Settings2, UserRound } from 'lucide-react';
import { useState } from 'react';
import { useTranslation } from 'react-i18next';
import { Link } from 'react-router-dom';
import Footer from '../components/Footer';
import Header from '../components/Header';
import { useTheme } from '../providers/ThemeProvider';

const orders = [{ name: 'AutoPro Garage', date: '12 августа 2026', status: 'orderCompleted', service: 'Диагностика ходовой' }, { name: 'MotorLab', date: '03 июля 2026', status: 'orderProgress', service: 'Замена масла' }];

export default function ProfilePage() {
  const { t, i18n } = useTranslation(); const { theme, toggleTheme } = useTheme();
  const [tab, setTab] = useState('personal'); const [saved, setSaved] = useState(false);
  const tabs = [{ id: 'personal', icon: UserRound }, { id: 'orders', icon: History }, { id: 'bonuses', icon: Coins }, { id: 'settings', icon: Settings2 }];
  return <div className="min-h-screen bg-slate-50 text-slate-900 dark:bg-slate-950 dark:text-slate-100"><Header /><main className="mx-auto max-w-7xl px-4 py-10 md:px-8"><Link to="/" className="text-sm font-medium text-cyan-600 dark:text-cyan-300">← {t('profile.back')}</Link><div className="mt-5"><p className="text-sm font-semibold text-cyan-600 dark:text-cyan-300">{t('nav.profile')}</p><h1 className="mt-1 text-4xl font-bold tracking-tight">{t('profile.title')}</h1><p className="mt-3 text-slate-500 dark:text-slate-400">{t('profile.subtitle')}</p></div><div className="mt-9 grid gap-6 lg:grid-cols-[265px_1fr]"><aside className="rounded-3xl border border-slate-200 bg-white p-3 shadow-soft dark:border-white/10 dark:bg-slate-900"><div className="mb-4 flex items-center gap-3 px-3 pt-2"><span className="grid h-11 w-11 place-items-center rounded-full bg-gradient-to-br from-cyan-400 to-blue-600 font-bold text-white">А</span><div><p className="font-semibold">Айбек Т.</p><p className="text-xs text-slate-500 dark:text-slate-400">aibek@example.kg</p></div></div><div className="flex gap-1 overflow-x-auto lg:block">{tabs.map(({ id, icon: Icon }) => <button key={id} onClick={() => setTab(id)} className={`mb-1 flex min-w-max w-full items-center gap-3 rounded-xl px-3 py-3 text-left text-sm font-medium transition ${tab === id ? 'bg-cyan-50 text-cyan-700 dark:bg-cyan-400/10 dark:text-cyan-300' : 'text-slate-600 hover:bg-slate-50 dark:text-slate-300 dark:hover:bg-white/5'}`}><Icon size={18} />{t(`profile.${id}`)}</button>)}</div></aside><section className="min-h-[430px] rounded-3xl border border-slate-200 bg-white p-6 shadow-soft dark:border-white/10 dark:bg-slate-900 md:p-8">{tab === 'personal' && <Personal t={t} saved={saved} onSave={() => { setSaved(true); setTimeout(() => setSaved(false), 2500); }} />}{tab === 'orders' && <Orders t={t} />}{tab === 'bonuses' && <Bonuses t={t} />}{tab === 'settings' && <Settings t={t} i18n={i18n} theme={theme} toggleTheme={toggleTheme} />}</section></div><a href="https://wa.me/996555123456" target="_blank" rel="noreferrer" className="mt-6 flex items-center justify-between rounded-2xl bg-emerald-500 px-5 py-4 text-white shadow-lg shadow-emerald-500/20 transition hover:bg-emerald-600"><div><p className="font-semibold">{t('profile.support')}</p><p className="mt-0.5 text-sm text-emerald-50">{t('profile.supportText')}</p></div><MessageCircle /></a></main><Footer /></div>;
}
function Personal({ t, saved, onSave }) { return <div><PanelTitle icon={<CircleUserRound />} title={t('profile.personal')} /><form onSubmit={(e) => { e.preventDefault(); onSave(); }} className="mt-7 grid gap-5 md:grid-cols-2"><Input label={t('profile.name')} defaultValue="Айбек Токтогулов" /><Input label={t('profile.phone')} defaultValue="+996 555 123 456" /><div className="md:col-span-2"><Input label={t('profile.email')} defaultValue="aibek@example.kg" type="email" /></div>{saved && <p className="md:col-span-2 rounded-xl bg-emerald-50 px-4 py-3 text-sm text-emerald-700 dark:bg-emerald-400/10 dark:text-emerald-300">{t('profile.saved')}</p>}<button className="inline-flex w-fit items-center gap-2 rounded-xl bg-slate-900 px-4 py-3 text-sm font-semibold text-white dark:bg-white dark:text-slate-900"><Save size={17} />{t('profile.save')}</button></form></div>; }
function Orders({ t }) { return <div><PanelTitle icon={<History />} title={t('profile.orders')} /><div className="mt-7 space-y-3">{orders.map((order) => <div key={order.date} className="flex flex-wrap items-center justify-between gap-4 rounded-2xl border border-slate-100 p-4 dark:border-white/10"><div><p className="font-semibold">{order.name}</p><p className="mt-1 text-sm text-slate-500 dark:text-slate-400">{order.service} · {order.date}</p></div><span className="rounded-full bg-cyan-50 px-3 py-1 text-xs font-medium text-cyan-700 dark:bg-cyan-400/10 dark:text-cyan-300">{t(`profile.${order.status}`)}</span></div>)}</div></div>; }
function Bonuses({ t }) { return <div><PanelTitle icon={<Coins />} title={t('profile.bonuses')} /><div className="mt-7 rounded-3xl bg-gradient-to-br from-cyan-500 to-blue-600 p-6 text-white"><p className="text-sm text-cyan-50">{t('profile.bonusBalance')}</p><p className="mt-2 text-5xl font-bold">760</p><p className="mt-4 text-sm text-cyan-50">{t('profile.bonusHint')}</p></div><div className="mt-5 space-y-3 text-sm"><Transaction text={t('profile.bonusEarned')} value="+120" positive /><Transaction text={t('profile.bonusSpent')} value="−100" /></div></div>; }
function Settings({ t, i18n, theme, toggleTheme }) { return <div><PanelTitle icon={<Settings2 />} title={t('profile.settings')} /><div className="mt-7 space-y-5"><div className="flex items-center justify-between rounded-2xl border border-slate-100 p-4 dark:border-white/10"><div className="flex items-center gap-3"><Globe2 className="text-cyan-500" /><p className="font-medium">{t('profile.language')}</p></div><select value={i18n.language} onChange={(e) => i18n.changeLanguage(e.target.value)} className="w-auto !bg-slate-100 !py-2 dark:!bg-white/10"><option value="ru">Русский</option><option value="ky">Кыргызча</option></select></div><div className="flex items-center justify-between rounded-2xl border border-slate-100 p-4 dark:border-white/10"><div className="flex items-center gap-3"><Palette className="text-cyan-500" /><div><p className="font-medium">{t('profile.appearance')}</p><p className="text-sm text-slate-500 dark:text-slate-400">{theme === 'dark' ? t('profile.dark') : t('profile.light')}</p></div></div><button onClick={toggleTheme} className="rounded-xl bg-slate-100 px-3 py-2 text-sm font-medium dark:bg-white/10">{theme === 'dark' ? t('profile.light') : t('profile.dark')}</button></div><div className="flex items-center gap-3 rounded-2xl border border-slate-100 p-4 dark:border-white/10"><Bell className="text-cyan-500" /><p className="font-medium">{t('header.notifications')}</p><span className="ml-auto h-6 w-11 rounded-full bg-cyan-500 p-1"><span className="block h-4 w-4 translate-x-5 rounded-full bg-white" /></span></div></div></div>; }
function PanelTitle({ icon, title }) { return <div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-cyan-50 text-cyan-600 dark:bg-cyan-400/10 dark:text-cyan-300">{icon}</span><h2 className="text-2xl font-bold">{title}</h2></div>; }
function Input({ label, ...props }) { return <label className="grid gap-2 text-sm font-medium"><span>{label}</span><input {...props} className="rounded-xl border border-slate-200 bg-slate-50 px-3 py-3 outline-none ring-cyan-500 transition focus:ring-2 dark:border-white/10 dark:bg-slate-950" /></label>; }
function Transaction({ text, value, positive }) { return <div className="flex justify-between rounded-xl bg-slate-50 px-4 py-3 dark:bg-white/5"><span>{text}</span><span className={positive ? 'font-semibold text-emerald-500' : 'font-semibold'}>{value}</span></div>; }
